language: python

env: PYTHON_BIN=python3

matrix:
  include:
    - os: linux
      python: 2.7
      env: PYTHON_BIN=python
    - os: linux
      dist: focal
      python: 3.4
    - os: linux
      dist: focal
      python: 3.5
    - os: linux
      dist: focal
      python: 3.6
    - os: linux
      dist: focal
      python: 3.7
    - os: linux
      dist: focal
      python: 3.8
    - os: linux
      dist: focal
      python: 3.9
    - os: linux
      dist: focal
      python: 3.10
    - os: osx
      language: generic
      env: PYTHON_BIN=python2
    - os: osx
      language: generic

script:
  - $PYTHON_BIN setup.py install
  - cd ..
  - $PYTHON_BIN -m sslpsk2.test
